### ISSUE TITLE
Compiled release available?

### ISSUE THREAD

**Issue by arturnovek** [eu-digital-green-certificates/dgc-cli#11]
In README.md there is text and link to releases.

Download latest build from Releases  ( link to https://github.com/eu-digital-green-certificates/dgc-cli/releases/tag/latest )
Linked releases page does not exist (Giving 404 error from GitHub)

**Comment by daniel-eder** [comment]
@arturnovek there is currently no latest tag, hence the 404, however you can find the available releases under https://github.com/eu-digital-green-certificates/dgc-cli/releases 

@f11h should we update the link to the general release page, or are you planning on keeping an up-to-date "latest" tag?

**Comment by f11h** [comment]
Oh yes, the link was wrong.

Github automatically provides a link to the latest release and I've put this one into the readme. Please have a look on my PR #12

**Comment by daniel-eder** [comment]
Closed in #12
