### ISSUE TITLE
Getting Error as missing subcommand while running bat file in windows 10

### ISSUE THREAD

**Issue by arunextasy** [eu-digital-green-certificates/dgc-cli#22]
Getting Error as missing subcommand while running bat file in windows 10

![image](https://user-images.githubusercontent.com/56584667/133400147-0b2d7feb-e029-4164-a9c1-10feed3633b7.png)

**Comment by cowboy-bebug** [comment]
@arunextasy The command must be provided (ie, they are not optional flags):
```console
> dgc.bat signing --help
> dgc.bat trustanchor --help
```
